server:
  #服务端口
  port: 9090
  #服务名称
  servlet:
    context-path: /springboot
#热部署
devtools:
  restart:
    enabled: true #热部署生效
    #设置重启的目录
    additional-paths: src/main/java
    exclude: WEB-INF/** #classpath目录下的WEB-INF文件夹内容修改不重启
spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/ssm
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        #数据库驱动
        driver-class-name: com.mysql.jdbc.Driver
        #druid监控拦截
        filters: stat
        #最大连接数
        maxActive: 20
        #初始化连接数
        initialSize: 1
        #最大等待响应时间（毫秒）
        maxWait: 60000
        #最小连接数
        minIdle: 1
        #配置心跳 检测需要关闭的空闲连接时间（毫秒）
        timeBetweenEvictionRunsMillis: 60000
        #连接在连接池中最小生存时间（毫秒）
        minEvictableIdleTimeMillis: 300000
        #检测连接是否有效
        validationQuery: select 'x'
        #建议配置为true，不影响性能，并且保证安全性。
        #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，
        #执行validationQuery检测连接是否有效。
        testWhileIdle: true
        #申请连接时执行validationQuery检测连接是否有效,设置true会降低性能
        #这里设置为true防止取到的链接不可用
        testOnBorrow: true
        #归还连接时执行validationQuery检测连接是否有效,设置true会降低性能
        testOnReturn: false
        #打开PSCache，并且指定每个连接上PSCache的大小  如果用Oracle，则把poolPreparedStatements配置为true，mysql可以配置为false。
        poolPreparedStatements: false
        maxOpenPreparedStatements: 20

mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: cn.piesat.springboot.entity  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
    #最主要配置，只配置此项就可以使用
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

#redis配置
redis:
  #数据库索引
  database: 0
  #服务器地址
  host: 127.0.0.1
  #服务器连接端口
  port: 6379
  #链接密码
  password:
  #链接池
  pool:
    #最大连接数（负值表示没有限制）
    max-active: 8
    #最大阻塞等待时间（负值表示没有限制）
    max-wait: 1
    #最大空闲链接
    max-idle: 8
    #最小空闲链接
    min-idle: 0
    #链接超时时间（毫秒）
  timeout: 0